import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ChartCard, Heatmap, HorizontalBarChart } from './DashboardCharts';
import { COLORS, percentTooltip } from './chartTheme';

export default function PolicyEdaCharts({ data }) {
  if (!data?.mode_share?.length) return <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">This CSV does not contain a recognized vehicle column, so transport-specific EDA is unavailable. The general dataset profile is still shown.</div>;
  const summary = data.summary ?? {};
  return <div className="grid min-w-0 grid-cols-1 gap-4 xl:grid-cols-2">
    <ChartCard title="Current Transport Mode Share" subtitle="Percentage of all survey respondents."><HorizontalBarChart data={data.mode_share} categoryKey="mode" valueKey="percentage" /></ChartCard>
    <ChartCard title="Alternatives Considered by Motorbike Users" subtitle="Multi-select responses; percentages do not sum to 100%."><HorizontalBarChart data={data.alternative_share} categoryKey="alternative" valueKey="percentage" color={COLORS.green} /></ChartCard>
    <ChartCard title="Consideration vs Future Vehicle Intention" subtitle="Comparison among car, E-bike and bike."><ResponsiveContainer width="100%" height="100%"><BarChart data={data.consideration_future}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="mode" /><YAxis tickFormatter={(value) => `${value}%`} /><Tooltip formatter={(value) => percentTooltip(value)} /><Legend /><Bar dataKey="considered" name="Considered after ban" fill={COLORS.blue} /><Bar dataKey="future_intention" name="Future vehicle intention" fill={COLORS.orange} /></BarChart></ResponsiveContainer></ChartCard>
    <ChartCard title="Transition Consideration Segments"><HorizontalBarChart data={data.transition_segments} categoryKey="segment" valueKey="percentage" color={COLORS.purple} categoryWidth={125} /></ChartCard>
    <ChartCard title="Number of Alternatives Considered" subtitle={`Average: ${summary.average_alternatives ?? 0} alternatives per motorbike user.`}><ResponsiveContainer width="100%" height="100%"><BarChart data={data.alternative_count}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="count" /><YAxis tickFormatter={(value) => `${value}%`} /><Tooltip formatter={(value) => percentTooltip(value)} /><Bar dataKey="percentage" name="Motorbike users" fill={COLORS.blue} /></BarChart></ResponsiveContainer></ChartCard>
    <ChartCard title="Car Consideration by Commute Distance"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.car_by_distance}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="distance" /><YAxis tickFormatter={(value) => `${value}%`} /><Tooltip formatter={(value) => percentTooltip(value)} /><Line type="monotone" dataKey="car" name="Consider Car" stroke={COLORS.red} strokeWidth={3} connectNulls /></LineChart></ResponsiveContainer></ChartCard>
    <ChartCard title="Alternative Consideration by Distance"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.alternatives_by_distance}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="distance" /><YAxis tickFormatter={(value) => `${value}%`} /><Tooltip formatter={(value) => percentTooltip(value)} /><Legend /><Line type="monotone" dataKey="car" name="Car" stroke={COLORS.red} strokeWidth={3} /><Line type="monotone" dataKey="bus" name="Bus" stroke={COLORS.blue} strokeWidth={3} /><Line type="monotone" dataKey="ebike" name="E-bike" stroke={COLORS.green} strokeWidth={3} /></LineChart></ResponsiveContainer></ChartCard>
    <ChartCard title="Public Transport Proximity"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.pt_proximity}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="group" tick={{ fontSize: 11 }} /><YAxis tickFormatter={(value) => `${value}%`} /><Tooltip formatter={(value) => percentTooltip(value)} /><Legend /><Bar dataKey="bus" name="Consider Bus" fill={COLORS.blue} /><Bar dataKey="car" name="Consider Car" fill={COLORS.red} /></BarChart></ResponsiveContainer></ChartCard>
    <ChartCard title="Perception and Alternative Consideration"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.perception}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="perception" /><YAxis tickFormatter={(value) => `${value}%`} /><Tooltip formatter={(value) => percentTooltip(value)} /><Legend /><Bar dataKey="car" name="Car" fill={COLORS.red} /><Bar dataKey="ebike" name="E-bike" fill={COLORS.green} /><Bar dataKey="bus" name="Bus" fill={COLORS.blue} /></BarChart></ResponsiveContainer></ChartCard>
    <ChartCard title="Car Consideration Heatmap"><Heatmap heatmap={data.occupation_distance_heatmap} /></ChartCard>
  </div>;
}
