const option = (value, label) => ({ value, label });
const ownership = [option('0', 'None'), option('1', '1'), option('2', '2'), option('3', '3'), option('4', '4'), option('more_5', '5 or more')];
const opinion = [option('verybad', 'Very bad'), option('bad', 'Bad'), option('neutral', 'Neutral'), option('good', 'Good'), option('verygood', 'Very good')];
const weeklyModeFrequency = [option('1_5', '1–5'), option('6_10', '6–10'), option('11_15', '11–15'), option('16_20', '16–20'), option('more_20', 'More than 20')];
const accessibility = [option('very_bad', 'Very bad'), option('bad', 'Bad'), option('neutral', 'Neutral'), option('good', 'Good'), option('very_good', 'Very good')];
const reasonNotUsed = [option('cost', 'Cost'), option('jam', 'Traffic congestion'), option('parking', 'Parking'), option('slow', 'Too slow'), option('unsafe', 'Safety')];
const yesNo = [option('1', 'Yes'), option('0', 'No')];

export const SURVEY_FIELDS = [
  { name: 'age', label: 'Age group', required: true, options: [option('less_18', 'Under 18'), option('18_25', '18–25'), option('26_35', '26–35'), option('36_55', '36–55'), option('56_75', '56–75'), option('more_75', 'Over 75')] },
  { name: 'occup', label: 'Occupation', required: true, options: [option('state', 'State sector'), option('private', 'Private sector'), option('fdi', 'Foreign-invested company'), option('student', 'Student'), option('retired', 'Retired')] },
  { name: 'gender', label: 'Gender', required: true, options: [option('male', 'Male'), option('female', 'Female'), option('prefer_not_to_say', 'Prefer not to say')] },
  { name: 'origlat', label: 'Origin latitude', type: 'number', required: true, min: 8, max: 24, step: 'any', location: true },
  { name: 'origlon', label: 'Origin longitude', type: 'number', required: true, min: 102, max: 110, step: 'any', location: true },
  { name: 'destlat', label: 'Destination latitude', type: 'number', required: true, min: 8, max: 24, step: 'any', location: true },
  { name: 'destlon', label: 'Destination longitude', type: 'number', required: true, min: 102, max: 110, step: 'any', location: true },
  { name: 'purp', label: 'Trip purpose', required: true, options: [option('work', 'Work'), option('education', 'Education'), option('shopping', 'Shopping'), option('leisure', 'Leisure'), option('visit', 'Visit friends or family'), option('caring', 'Care responsibilities')] },
  { name: 'vehic', label: 'Current vehicle', required: true, options: [option('moto', 'Motorbike'), option('car', 'Car'), option('ebike', 'E-bike'), option('bike', 'Bicycle'), option('walk', 'Walk'), option('bus', 'Bus'), option('taxi', 'Taxi'), option('tram', 'Tram')] },
  { name: 'freqpweek', label: 'Trips per week', required: true, options: [option('1_3', '1–3'), option('4_7', '4–7'), option('8_10', '8–10'), option('11_13', '11–13'), option('14_16', '14–16'), option('17_20', '17–20'), option('more_20', 'More than 20')] },
  { name: 'OD_dist', label: 'Origin-destination distance (km)', type: 'number', min: 0, max: 300, step: 'any' },
  { name: 'travtime', label: 'Travel time (minutes)', type: 'number', min: 0, max: 1440, step: 'any' },
  { name: 'reason', label: 'Reason for current mode', options: [option('convinient', 'Convenience'), option('timesaving', 'Time saving'), option('cost', 'Cost'), option('other', 'Other'), option('convinient timesaving', 'Convenience and time saving'), option('cost convinient', 'Cost and convenience'), option('cost timesaving', 'Cost and time saving'), option('convinient other', 'Convenience and other'), option('timesaving other', 'Time saving and other'), option('cost other', 'Cost and other'), option('convinient timesaving other', 'Convenience, time saving and other'), option('cost convinient timesaving', 'Cost, convenience and time saving'), option('cost convinient other', 'Cost, convenience and other'), option('cost timesaving other', 'Cost, time saving and other'), option('cost convinient timesaving other', 'All listed reasons')] },
  { name: 'own_car', label: 'Cars owned', options: ownership },
  { name: 'own_motob', label: 'Motorbikes owned', options: ownership },
  { name: 'own_ebike', label: 'E-bikes owned', options: ownership },
  { name: 'own_bike', label: 'Bicycles owned', options: ownership },
  { name: 'freq_car', label: 'Weekly car trips', options: weeklyModeFrequency },
  { name: 'freq_motob', label: 'Weekly motorbike trips', options: weeklyModeFrequency },
  { name: 'freq_ebike', label: 'Weekly e-bike trips', options: weeklyModeFrequency },
  { name: 'freq_bike', label: 'Weekly bicycle trips', options: weeklyModeFrequency },
  { name: 'freq_taxi', label: 'Weekly taxi trips', options: weeklyModeFrequency },
  { name: 'freq_bus', label: 'Weekly bus trips', options: weeklyModeFrequency },
  { name: 'school_acc', label: 'Access to schools', options: accessibility },
  { name: 'market_acc', label: 'Access to markets', options: accessibility },
  { name: 'hosp_acc', label: 'Access to hospitals', options: accessibility },
  { name: 'bank_acc', label: 'Access to banks', options: accessibility },
  { name: 'leis_acc', label: 'Access to leisure', options: accessibility },
  { name: 'type', label: 'Housing type', options: [option('high_rise', 'High-rise apartment'), option('old_building', 'Old apartment building'), option('private_house', 'Private house'), option('private_new', 'New private development'), option('resettlement', 'Resettlement housing'), option('social_house', 'Social housing')] },
  { name: 'status', label: 'Residency status', options: [option('long_stay', 'Long stay'), option('permanent', 'Permanent'), option('short_stay', 'Short stay')] },
  { name: 'own', label: 'Home tenure', options: [option('morgate', 'Mortgage'), option('owner', 'Owner'), option('parent_house', "Parents' home"), option('rent', 'Rent')] },
  { name: 'reas_not_car', label: 'Main reason not to use a car', options: reasonNotUsed },
  { name: 'reas_not_motob', label: 'Main reason not to use a motorbike', options: reasonNotUsed },
  { name: 'reas_not_ebike', label: 'Main reason not to use an e-bike', options: reasonNotUsed },
  { name: 'reas_not_bike', label: 'Main reason not to use a bicycle', options: reasonNotUsed },
  { name: 'dist_to_pub', label: 'Distance to public transport (m)', type: 'number', min: 0, max: 10000, step: 'any' },
  { name: 'aware_ban', label: 'Aware of vehicle ban', options: [option('yes', 'Yes'), option('no', 'No'), option('donotcare', 'Do not care')] },
  { name: 'fut_veh', label: 'Future vehicle preference', options: [option('moto', 'Motorbike'), option('car', 'Car'), option('ebike', 'E-bike'), option('bike', 'Bicycle'), option('no', 'No vehicle planned')] },
  { name: 'alt_car', label: 'Would consider car as an alternative', options: yesNo },
  { name: 'alt_ebike', label: 'Would consider e-bike as an alternative', options: yesNo },
  { name: 'alt_bike', label: 'Would consider bicycle as an alternative', options: yesNo },
  { name: 'alt_bus', label: 'Would consider bus as an alternative', options: yesNo },
  { name: 'alt_ltrain', label: 'Would consider light rail as an alternative', options: yesNo },
  { name: 'alt_taxi', label: 'Would consider taxi as an alternative', options: yesNo },
  { name: 'alt_walk', label: 'Would consider walking as an alternative', options: yesNo },
  { name: 'opinion_car', label: 'Opinion of car', options: opinion },
  { name: 'opinion_motob', label: 'Opinion of motorbike', options: opinion },
  { name: 'opinion_ebike', label: 'Opinion of e-bike', options: opinion },
  { name: 'opinion_bike', label: 'Opinion of bicycle', options: opinion },
  { name: 'opinion_taxi', label: 'Opinion of taxi', options: opinion },
  { name: 'opinion_bus', label: 'Opinion of bus', options: opinion },
  { name: 'opinion_ban', label: 'Opinion of vehicle ban', options: [option('strongdisagree', 'Strongly disagree'), option('disagree', 'Disagree'), option('neutral', 'Neutral'), option('agree', 'Agree'), option('strongagree', 'Strongly agree')] },
];
